# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TileGenerator.ui'
#
# Created: Sun Nov  4 13:26:24 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_TileGenerator_UI(object):
    def setupUi(self, TileGenerator_UI):
        TileGenerator_UI.setObjectName(_fromUtf8("TileGenerator_UI"))
        TileGenerator_UI.resize(507, 241)
        self.buttonBox = QtGui.QDialogButtonBox(TileGenerator_UI)
        self.buttonBox.setGeometry(QtCore.QRect(50, 200, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.widget = QtGui.QWidget(TileGenerator_UI)
        self.widget.setGeometry(QtCore.QRect(130, 10, 261, 92))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.output_path = QtGui.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.output_path.setFont(font)
        self.output_path.setObjectName(_fromUtf8("output_path"))
        self.verticalLayout.addWidget(self.output_path)
        self.xml_file = QtGui.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.xml_file.setFont(font)
        self.xml_file.setObjectName(_fromUtf8("xml_file"))
        self.verticalLayout.addWidget(self.xml_file)
        self.border_file = QtGui.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.border_file.setFont(font)
        self.border_file.setObjectName(_fromUtf8("border_file"))
        self.verticalLayout.addWidget(self.border_file)
        self.widget1 = QtGui.QWidget(TileGenerator_UI)
        self.widget1.setGeometry(QtCore.QRect(130, 110, 81, 60))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget1)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.units_pixel = QtGui.QLineEdit(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.units_pixel.setFont(font)
        self.units_pixel.setObjectName(_fromUtf8("units_pixel"))
        self.verticalLayout_3.addWidget(self.units_pixel)
        self.thread_count = QtGui.QLineEdit(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.thread_count.setFont(font)
        self.thread_count.setObjectName(_fromUtf8("thread_count"))
        self.verticalLayout_3.addWidget(self.thread_count)
        self.widget2 = QtGui.QWidget(TileGenerator_UI)
        self.widget2.setGeometry(QtCore.QRect(10, 10, 114, 91))
        self.widget2.setObjectName(_fromUtf8("widget2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.textLabel1 = QtGui.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.textLabel1.setFont(font)
        self.textLabel1.setObjectName(_fromUtf8("textLabel1"))
        self.verticalLayout_2.addWidget(self.textLabel1)
        self.textLabel1_4 = QtGui.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.textLabel1_4.setFont(font)
        self.textLabel1_4.setObjectName(_fromUtf8("textLabel1_4"))
        self.verticalLayout_2.addWidget(self.textLabel1_4)
        self.textLabel1_5 = QtGui.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.textLabel1_5.setFont(font)
        self.textLabel1_5.setObjectName(_fromUtf8("textLabel1_5"))
        self.verticalLayout_2.addWidget(self.textLabel1_5)
        self.widget3 = QtGui.QWidget(TileGenerator_UI)
        self.widget3.setGeometry(QtCore.QRect(11, 110, 111, 61))
        self.widget3.setObjectName(_fromUtf8("widget3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.widget3)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.textLabel1_3 = QtGui.QLabel(self.widget3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.textLabel1_3.setFont(font)
        self.textLabel1_3.setObjectName(_fromUtf8("textLabel1_3"))
        self.verticalLayout_4.addWidget(self.textLabel1_3)
        self.textLabel1_2 = QtGui.QLabel(self.widget3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.textLabel1_2.setFont(font)
        self.textLabel1_2.setObjectName(_fromUtf8("textLabel1_2"))
        self.verticalLayout_4.addWidget(self.textLabel1_2)
        self.widget4 = QtGui.QWidget(TileGenerator_UI)
        self.widget4.setGeometry(QtCore.QRect(400, 10, 100, 95))
        self.widget4.setObjectName(_fromUtf8("widget4"))
        self.gridLayout = QtGui.QGridLayout(self.widget4)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.output_browse = QtGui.QPushButton(self.widget4)
        self.output_browse.setObjectName(_fromUtf8("output_browse"))
        self.gridLayout.addWidget(self.output_browse, 0, 0, 1, 1)
        self.xml_browse = QtGui.QPushButton(self.widget4)
        self.xml_browse.setObjectName(_fromUtf8("xml_browse"))
        self.gridLayout.addWidget(self.xml_browse, 1, 0, 1, 1)
        self.border_browse = QtGui.QPushButton(self.widget4)
        self.border_browse.setObjectName(_fromUtf8("border_browse"))
        self.gridLayout.addWidget(self.border_browse, 2, 0, 1, 1)

        self.retranslateUi(TileGenerator_UI)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), TileGenerator_UI.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), TileGenerator_UI.reject)
        QtCore.QMetaObject.connectSlotsByName(TileGenerator_UI)

    def retranslateUi(self, TileGenerator_UI):
        TileGenerator_UI.setWindowTitle(QtGui.QApplication.translate("TileGenerator_UI", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.output_path.setToolTip(QtGui.QApplication.translate("TileGenerator_UI", "Path where to output tiles", None, QtGui.QApplication.UnicodeUTF8))
        self.xml_file.setToolTip(QtGui.QApplication.translate("TileGenerator_UI", "Mapnik xml file to be used for tile generation", None, QtGui.QApplication.UnicodeUTF8))
        self.border_file.setToolTip(QtGui.QApplication.translate("TileGenerator_UI", "Closed shapefile with extents", None, QtGui.QApplication.UnicodeUTF8))
        self.units_pixel.setToolTip(QtGui.QApplication.translate("TileGenerator_UI", "Units per pixel", None, QtGui.QApplication.UnicodeUTF8))
        self.thread_count.setToolTip(QtGui.QApplication.translate("TileGenerator_UI", "How many threads to use in tile generation", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel1.setText(QtGui.QApplication.translate("TileGenerator_UI", "Output Path:", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel1_4.setText(QtGui.QApplication.translate("TileGenerator_UI", "Mapnik XML file", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel1_5.setText(QtGui.QApplication.translate("TileGenerator_UI", "Border shapefile", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel1_3.setText(QtGui.QApplication.translate("TileGenerator_UI", "Units per Pixel:", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel1_2.setText(QtGui.QApplication.translate("TileGenerator_UI", "Thread Count:", None, QtGui.QApplication.UnicodeUTF8))
        self.output_browse.setText(QtGui.QApplication.translate("TileGenerator_UI", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.xml_browse.setText(QtGui.QApplication.translate("TileGenerator_UI", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.border_browse.setText(QtGui.QApplication.translate("TileGenerator_UI", "Browse", None, QtGui.QApplication.UnicodeUTF8))

